### ISSUE TITLE
Remove 'salesforce_' prefix from Table/Object names

### ISSUE THREAD

**Issue by d416** [turbot/steampipe-plugin-salesforce#16]
**Is your feature request related to a problem? Please describe.**
When querying, having to type out in full 'salesforce_' prefix before any Salesforce object name is cumbersome, time consming, and prone to errors.  For example, instead of typing 

select * from my_custom_object__c

the plugin expects salesforce_my_custom_object__c  which is an extra 11 characters. 

**Describe the solution you'd like**
Remove the pre-pending of the string 'salesforce_' to object names in the plugin.go file

**Describe alternatives you've considered**
The alternative is to type 'salesforce_' each time a table is referenced in a query.

**Additional context**
It's unclear why the salesforce_ string is pre-pended, but I was able to remove this in the plugin code and it worked beautifully.

**Comment by cbruno10** [comment]
@d416 Similar to my proposal in https://github.com/turbot/steampipe-plugin-salesforce/issues/13#issuecomment-1485697179, if we were to add a config arg that let you toggle whether or not the `salesforce_` prefix was added to table names, would that help in your use case?

We originally added the prefix to help group the tables together as part of `.inspect`, since we have some static tables like `salesforce_opportunity` in the plugin, but I can see how it's extra work each time when querying if you know the object name.

**Comment by d416** [comment]
Sure having a config would work.  After I submitted this FR I realized that the steampipe plugin sdk docs state that a prefix should be defined, I guess to differentiate it from other plugins?  Maybe this is best practice, but with FDW this is certainly not required, so I guess a configurable option could satisfy both plugin compliance and user convenience.  Thanks for getting back
